name: Setup SHA
description: Sets up $SHA

runs:
  using: composite
  steps:
    - name: ci-setup | short-sha
      uses: benjlevesque/short-sha@v3.0
        id: short-sha

    - name: ci-setup | $SHA
      shell: bash
      run: |
          echo 'SHA=${{ steps.short-sha.outputs.sha }}' >> $GITHUB_ENV
