# wjdlz/NOTE: ci@1.0.5
name: apps-desktop

on:
  push:
    branches: [timeline]
    paths:
      - '.github/workflows/apps-desktop.yml'
    tags:
      - '*/ci' # @suites-hq@1.0.5@timeline/ci, @suites-hq@1.0.5@dev/ci, ...

jobs:
  deployer:
    name: ${{github.ref_name}}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.yml@timeline
    secrets: inherit
    permissions:
      contents: write
    with:
      CALLER: ${{github.ref_name}}
