# wjdlz/NOTE: ci@1.0.5
name: apps-desktop | wf

on:
  push:
    branches: [timeline, deploy/dev, deploy/qa, deploy/preview, deploy/prod]
    paths:
      - '.github/workflows/apps-desktop.yml'
      - 'v/handbooks/ci.md'
    tags:
      - 'ci@deployer*'

jobs:
  deployer:
    name: apps-desktop | ${{github.ref_name}}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.yml@timeline
    secrets: inherit
    permissions:
      contents: write
    with:
      CALLER: ${{github.ref_name}}
