# wjdlz/NOTE: ci@1.0.4-trigger
name: QA | wf

on:
  push:
    branches: [timeline]
    paths:
      - '.github/workflows/qa.yml'
      - 'v/handbooks/ci.md'
    tags:
      - 'v*'

env:
  REPO: ${{ inputs.GIT_REPO || 'vezham/v0xFE-apps-desktop' }}
  BRANCH: ${{ inputs.GIT_BRANCH || 'timeline' }}
  CI_DIR: ./v/bin/ci
  # ENTRY_POINT: ./
  # DX_APP_PATH:
  # DX_APP_NAME:
  # NX_APP_NAME:
  
jobs:
  build:
    name: Build
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [9.6.0]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        # uses: ./.github/common-actions/install
        uses: ./.github/actions/setup-install/action.yml

      - name: Build packages
        run: pnpm make

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        # uses: ./.github/common-actions/install
        uses: ./.github/actions/setup-install

      - name: Run tests
        # run: pnpm test
        run: pnpm --version

  # eslint:
  #   name: ESLint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v4

  #     - name: Install
  #       uses: ./.github/common-actions/install

  #     - name: Run ESLint
  #       run: pnpm lint

  # types:
  #   name: TypeScript
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v4

  #     - name: Install
  #       uses: ./.github/common-actions/install

  #     - name: Run typecheck
  #       run: pnpm typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run prettier
        run: pnpm format:check
