# wjdlz/NOTE: ci@1.0.5
name: TVA

on:
  push:
    branches: [-timeline]
    # paths:
    #   - '.github/workflows/tva.yml'
    # tags:
    #   - '*/ci' # wjdlz/NOTE: v/handbooks/tags.md

jobs:
  deployer:
    name: ${{github.ref_name}}
    uses: vezham/v0xFE-deployer/.github/workflows/tva.yml@timeline
    secrets: inherit
    permissions:
      contents: write
    with:
      CALLER: ${{github.ref_name}}
