# wjdlz/NOTE: ci@1.0.4
name: TVA | wf

on:
  push:
    branches: [timeline]
    paths:
      - '.github/workflows/tva.yml'
      - 'v/handbooks/ci.md'
    # tags:
    #   - 'v*'

env:
  REPO: ${{ inputs.GIT_REPO || 'vezham/v0xFE-apps-desktop' }}
  BRANCH: ${{ inputs.GIT_BRANCH || 'timeline' }}
  CI_DIR: ./v/bin/ci
  # ENTRY_POINT: ./
  # DX_APP_PATH:
  # DX_APP_NAME:
  # NX_APP_NAME:

jobs:
  tva:
    name: TVA
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20]
        pnpm-version: [9.6.0]
    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ${{ env.ENTRY_POINT }}
    permissions:
      contents: write
      # actions: read
      # checks: write

    steps:
      - name: checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.BRANCH }}

      - name: setup | node & pnpm
        uses: ./.github/actions/setup-install

  format:
    name: Format (pkg,prettier) & Lint (eslint,stylelint)
    runs-on: ubuntu-latest

    steps:
      - name: checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.BRANCH }}

      - name: setup | node & pnpm
        uses: ./.github/actions/setup-install

      - name: cli | format
        run: pnpm format

  # tests:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: checkout | ${{ env.REPO }}@${{ env.BRANCH }}
  #       uses: actions/checkout@v4
  #       with:
  #         repository: ${{ env.REPO }}
  #         ref: ${{ env.BRANCH }}

  #     - name: setup | node & pnpm
  #       uses: ./.github/actions/setup-install

  #     - name: cli | tests
  #       run: pnpm test

  # types:
  #   name: TypeScript
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: checkout | ${{ env.REPO }}@${{ env.BRANCH }}
  #       uses: actions/checkout@v4
  #       with:
  #         repository: ${{ env.REPO }}
  #         ref: ${{ env.BRANCH }}

  #     - name: setup | node & pnpm
  #       uses: ./.github/actions/setup-install

  #     - name: cli | typecheck
  #       run: pnpm typecheck

  # build:
  #   name: Build
